# Generated by Django 5.1 on 2024-12-13 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_marca_talla_producto_marca_producto_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendaApp.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ManyToManyField(blank=True, related_name='productos', to='tiendaApp.talla'),
        ),
    ]
