# Generated by Django 5.1 on 2025-01-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0006_imagencategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='talla',
        ),
    ]
