# Generated by Django 5.1 on 2025-01-28 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0009_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('idtipopedido', models.AutoField(primary_key=True, serialize=False)),
                ('tipopedido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('productos', models.JSONField()),
                ('fecha', models.DateField()),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('idtipopedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tiendaApp.tipopedido')),
            ],
        ),
    ]
