# Generated by Django 5.1 on 2025-01-28 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0011_alter_pedido_idtipopedido_alter_pedido_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
