# Generated by Django 5.1 on 2025-01-28 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0012_alter_pedidoproducto_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('idtipotransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipotransaccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('idtransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=3)),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('pagodirecto', models.BooleanField(default=False)),
                ('codigoreferencia', models.CharField(blank=True, max_length=255, null=True)),
                ('idtipopago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='tiendaApp.tipotransaccion')),
                ('idusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='transaccion',
            field=models.ManyToManyField(related_name='pedidos', to='tiendaApp.transaccion'),
        ),
    ]
