# Generated by Django 5.1 on 2025-01-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0013_tipotransaccion_transaccion_pedido_transaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='idtipopago',
            new_name='idtipotransaccion',
        ),
    ]
