# Generated by Django 5.1 on 2025-01-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0014_rename_idtipopago_transaccion_idtipotransaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='transaccion',
            new_name='transacciones',
        ),
    ]
